target 'ProductionCreateTest' do
#    自动布局
	pod 'PureLayout', '~> 3.1.2'
#    监听
	pod 'ReactiveObjC', '~> 3.1.0'
#    多图片网络w缓存
    pod 'SDWebImage', '~> 4.4.2'
#    网络监测
    pod 'Reachability', '~> 3.2'
#    本地数据库
    pod 'FMDB', '~> 2.7.5'
#    网络请求组件
    pod 'AFNetworking', '~> 3.2.1'
#    数据解析
    pod 'YYModel', '~> 1.0.4'
#    上下拉刷新
    pod 'MJRefresh', '~> 3.1.15.7'
#    tableView collectionview空白页面展示
    pod 'DZNEmptyDataSet', '~> 1.8.0'
#    自定义布局yytext yylabel
    pod 'YYText', '~> 1.0.7'
end
